### ISSUE TITLE
Is turf-swift supporting all Turf.js features?

### ISSUE THREAD

**Issue by zhouhao27** [mapbox/turf-swift#136]
I'm wondering if turf-swift supporting all Turf.js features? I'd like to calculate the distance from a point to a polygon so that I may need `nearestPointOnLine`, but I didn't find it. Any idea? Thanks.

**Comment by 1ec5** [comment]
The equivalent method is `LineString.closestCoordinate(to:)`. If you’re used to Turf.js, [this comparison table](https://github.com/mapbox/turf-swift#available-functionality) may help you find the equivalent Swift methods in the future.

turf-swift doesn’t currently support every Turf.js function. Some are unnecessary because Core Location and Foundation already provide similar functionality. Others are desirable but we just haven’t gotten a chance to port them to Swift yet. If you’re interested in a particular function but there isn’t a Swift equivalent, please open another issue – or contribute an implementation if you’re familiar enough with JavaScript and Swift to do so. Thank you!
