### ISSUE TITLE
Project Vision?

### ISSUE THREAD

**Issue by okcoker** [mapbox/turf-swift#139]
Hi I'm working on a project that needs a subset of these turf functions and while I was [porting some](https://github.com/mapbox/turf-swift/pulls/okcoker) over, I tried to go on to port some boolean functions next. I hit a bit of a rough patch as I noticed things implemented in this library like `intersection` don't necessarily follow the same patterns as what's in Turf.js.

When I first started messing around with turf-swift I noticed ["GeoJSON was experimental"](https://github.com/mapbox/turf-swift/tree/23e72d4174eacd76cc6414f063b427d2dac81cfb#geojson) so I sort of stayed away from it. Getting deeper into the lib, it seems more unavoidable if the goal is for the whole library to be ported over.

My question is how do you see this library being structured moving forward? Seems like some functions have been added in a bit randomly, some of which aren't even named the same as original turf functions. The Java version has them organized [by module](https://github.com/mapbox/mapbox-java/tree/f16813f3489269011ebacfce8a56fa6b5b3279f4/services-turf/src/test/java/com/mapbox/turf). The Java version also uses a bunch of [overloaded functions](https://github.com/mapbox/mapbox-java/blob/f16813f3489269011ebacfce8a56fa6b5b3279f4/services-turf/src/main/java/com/mapbox/turf/TurfTransformation.java#L36-L67) which may be desirable? I recently noticed the `Geometry.swift` module here. Was the idea of this to basically pass `Geometry` around to avoid these overloaded functions? Maybe it would be used in a context [like this](https://github.com/okcoker/turf-swift/blob/cf622d836f0813e55fd196bfb9c2c982c409f8f3/Sources/Turf/Boolean/Disjoint.swift#L43-L84) so we could prevent the use of `Any`?

How much should I consider the GeoJSON file moving forward? A lot of the turf helper functions accept GeoJSON so should these helper functions also be ported? The Java version has them as a [part of the GeoJSON module](https://github.com/mapbox/mapbox-java/blob/f16813f3489269011ebacfce8a56fa6b5b3279f4/docs/turf-port.md) which seems like it makes sense. I also prefer that checklist in general as compared to the table in the readme here. It makes it a lot clearer as to what functions have been ported.

On a related note has any work been done with [Rbush](https://github.com/mapbox/turf-swift/issues/37) mentioned here? Since that is a dependency of `booleanIntersects` I was wondering where the thinking here was left off in terms of using GKRTree or making a custom port of RBush?

I know the tests are an important part of any contribution here regardless of the structure moving forward but while I'm here, I'd like to follow whatever the vision for the project is/was.

**Comment by 1ec5** [comment]
> When I first started messing around with turf-swift I noticed ["GeoJSON was experimental"](https://github.com/mapbox/turf-swift/tree/23e72d4174eacd76cc6414f063b427d2dac81cfb#geojson) so I sort of stayed away from it. Getting deeper into the lib, it seems more unavoidable if the goal is for the whole library to be ported over.

GeoJSON support has been stable since v1.0.0. cafaad1aa840253b32db98a8d9509a845a9c547f removes the note from the readme. Thanks for noticing that.

> My question is how do you see this library being structured moving forward? Seems like some functions have been added in a bit randomly, some of which aren't even named the same as original turf functions. The Java version has them organized [by module](https://github.com/mapbox/mapbox-java/tree/f16813f3489269011ebacfce8a56fa6b5b3279f4/services-turf/src/test/java/com/mapbox/turf). The Java version also uses a bunch of [overloaded functions](https://github.com/mapbox/mapbox-java/blob/f16813f3489269011ebacfce8a56fa6b5b3279f4/services-turf/src/main/java/com/mapbox/turf/TurfTransformation.java#L36-L67) which may be desirable? I recently noticed the `Geometry.swift` module here. Was the idea of this to basically pass `Geometry` around to avoid these overloaded functions? Maybe it would be used in a context [like this](https://github.com/okcoker/turf-swift/blob/cf622d836f0813e55fd196bfb9c2c982c409f8f3/Sources/Turf/Boolean/Disjoint.swift#L43-L84) so we could prevent the use of `Any`?

Turf.js itself has been rewritten and reorganized several times since the turf-swift project started. For our part, the goal of this project is to present the same functionality while adhering to the [Swift API design guidelines](https://swift.org/documentation/api-design-guidelines/). This necessarily means the API differs from Turf.js’s JavaScript-centric approach, particularly when it comes to object orientation. There are also some situations where it makes more sense to piggyback on existing Foundation and Core Location types rather than roll our own homegrown types.

We’re not averse to method overloads, but they should be less frequently required because we generally define methods on the relevant types. Geometry.swift is intended to represent GeoJSON geometries, nothing more. To share methods across unrelated types without duplicating code, consider defining a protocol with a default implementation and having multiple types adopt that protocol.

> How much should I consider the GeoJSON file moving forward? A lot of the turf helper functions accept GeoJSON so should these helper functions also be ported? The Java version has them as a [part of the GeoJSON module](https://github.com/mapbox/mapbox-java/blob/f16813f3489269011ebacfce8a56fa6b5b3279f4/docs/turf-port.md) which seems like it makes sense. I also prefer that checklist in general as compared to the table in the readme here. It makes it a lot clearer as to what functions have been ported.

A checklist would be reasonable as long as it remains up-to-date. We had some problems early on with Turf.js functions getting renamed frequently, but that’s probably no longer as much of an issue. That said, maybe it would be more effective to open issues for each missing function, to label with <kbd>JS parity</kbd>.

> On a related note has any work been done with [Rbush](https://github.com/mapbox/turf-swift/issues/37) mentioned here? Since that is a dependency of `booleanIntersects` I was wondering where the thinking here was left off in terms of using GKRTree or making a custom port of RBush?

I don’t think there’s been any movement within this project so far, but feel free to explore those ideas further.

**Comment by okcoker** [comment]
Great thanks, Minh. This was helpful.
