### ISSUE TITLE
Add method to slice LineString between two distances

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/turf-swift#156]
Right now in `Turf.js`, there's a method to slice a `LineString` based on the start and end distance, as [TurfMisc.lineSliceAlong(line: startDist: stopDist: options)](https://github.com/Turfjs/turf/tree/master/packages/turf-line-slice-along/).

And right now in `Turf.swift`, we have the `LineString.trimmed(from:distance)` to slice a `LineString` based on the start coordinate and the distance.

So is there any way to slice a `LineString` based on the start and end distance? Right now I'm implementing the following method to do so, but not sure whether it would get the same result as `TurfMisc.lineSliceAlong(line: lineString, startDist: startDistance, stopDist: stopDistance)`

```
if let midPoint = lineString.coordinateFromStart(distance: startDistance) {
    let slicedLine = lineString.trimmed(from: midPoint, distance: stopDistance - startDistance)
}
```

**Comment by 1ec5** [comment]
The code above is how you’d implement the same behavior. I think Turf.js’s `line-slice-along` originally did the same thing as `LineString.trimmed(from:distance:)` does today, but it must’ve been modified at some point to take a starting distance instead of a starting coordinate. We should add a variant of `trimmed(from:to:)` that takes two distances instead of a coordinate and distance.
