### ISSUE TITLE
Missing GeometryCollection support

### ISSUE THREAD

**Issue by bryanrahn** [mapbox/turf-swift#89]
Will this be supported eventually, or was it intentionally left out?

**Comment by 1ec5** [comment]
Looks like it was an oversight. This library definitely needs to support all the types specified in the GeoJSON specification; otherwise, it could fail to decode perfectly valid GeoJSON.

**Comment by bryanrahn** [comment]
Exactly; I'm seeing `FeatureCollectionTests` fail if I swap out it's `geoJSON` file with one that has `GeometryCollection`

**Comment by 1ec5** [comment]
I took a quick look at it, but it looks like it’s going to be difficult to implement GeometryCollection until we revamp the GeoJSON model objects in #91. Otherwise, the fact that there’s no single type representing all geometries means it’s very awkward to represent GeometryCollection’s heterogeneous collection of geometries, a particular problem when it comes to conforming to Equatable.
